// Generated by build.mjs from content/site.json.
window.CANNACON_CONFIG = {
  "ageRememberDays": 180,
  "privacyRememberDays": 180,
  "media": {
    "heroImage": "https://cannacon.org/wp-content/uploads/DSC2681-1-1200x800-2.jpg",
    "heroVideo": "https://cannacon.org/wp-content/uploads/EXHIBITOR-MONTAGE-1.mp4",
    "heroVideoAutoplay": false,
    "youtubeEmbed": "https://www.youtube-nocookie.com/embed/UnAv5nVQzks",
    "showFloor": "https://cannacon.org/wp-content/uploads/DSC2681-1-1200x800-2.jpg",
    "conversations": "https://cannacon.org/wp-content/uploads/CannaCon2019_MSP_013119-202.jpg",
    "community": "https://cannacon.org/wp-content/uploads/DSC2699-1200x800-1.jpg"
  },
  "forms": {
    "exhibitor": {
      "title": "Exhibitor inquiry",
      "subject": "CannaCon | Exhibitor Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft",
      "endpoint": null
    },
    "speaker": {
      "title": "Speaker & programming inquiry",
      "subject": "CannaCon | Speaker Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft",
      "endpoint": null
    },
    "sponsor": {
      "title": "Sponsor & partnership inquiry",
      "subject": "CannaCon | Sponsor Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft",
      "endpoint": null
    },
    "buyer": {
      "title": "Hosted Buyer Request",
      "subject": "Infused Product Expo | Hosted Buyer Request",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft",
      "endpoint": null
    },
    "contact": {
      "title": "Contact CannaCon",
      "subject": "CannaCon | General Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft",
      "endpoint": null
    }
  },
  "events": [
    {
      "code": "VA27"
    },
    {
      "code": "LV27"
    },
    {
      "code": "MN27"
    }
  ]
};
