// Generated by build.mjs from content/site.json.
window.CANNACON_CONFIG = {
  "ageRememberDays": 180,
  "privacyRememberDays": 180,
  "media": {
    "heroImage": "https://cannacon.org/wp-content/uploads/DSC2681-1-1200x800-2.jpg",
    "heroVideo": "https://cannacon.org/wp-content/uploads/EXHIBITOR-MONTAGE-1.mp4",
    "heroVideoAutoplay": false,
    "heroVideoNote": "Remote original is not yet size-optimized. Manual play protects loading time until an optimized local loop is supplied.",
    "youtubeEmbed": "https://www.youtube-nocookie.com/embed/UnAv5nVQzks",
    "showFloor": "https://cannacon.org/wp-content/uploads/DSC2681-1-1200x800-2.jpg",
    "conversations": "https://cannacon.org/wp-content/uploads/CannaCon2019_MSP_013119-202.jpg",
    "community": "https://cannacon.org/wp-content/uploads/DSC2699-1200x800-1.jpg"
  },
  "forms": {
    "exhibitor": {
      "title": "CannaCon Exhibitor & General Inquiry",
      "subject": "CannaCon | Exhibitor Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft"
    },
    "speaker": {
      "title": "CannaCon Speaker & Education Inquiry",
      "subject": "CannaCon | Speaker Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft"
    },
    "sponsor": {
      "title": "CannaCon Sponsor & Partnership Inquiry",
      "subject": "CannaCon | Sponsor Inquiry",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft"
    },
    "buyer": {
      "title": "Infused Product Expo | Hosted Buyer Request",
      "subject": "Infused Product Expo | Hosted Buyer Request",
      "recipient": "lucas@cannacon.org",
      "mode": "email-draft"
    }
  },
  "tickets": [
    {
      "id": "day1",
      "name": "1-day pass",
      "price": 40,
      "description": "One expo day, including general seminars.",
      "includes": "Choose your day. The separately ticketed financial course is not included."
    },
    {
      "id": "two",
      "name": "2-day pass",
      "price": 80,
      "description": "Both expo days, including general seminars.",
      "includes": "The separately ticketed financial course is not included."
    },
    {
      "id": "all",
      "name": "All-access pass",
      "price": 100,
      "description": "Both expo days plus pre-show networking events.",
      "includes": "General seminars included. The financial course is sold separately."
    }
  ],
  "courses": [
    {
      "id": "s1",
      "name": "Session 1",
      "price": 100,
      "durationHours": 3,
      "dayIndex": 0
    },
    {
      "id": "s2",
      "name": "Session 2",
      "price": 300,
      "durationHours": 3,
      "dayIndex": 1
    },
    {
      "id": "s3",
      "name": "Session 3",
      "price": 300,
      "durationHours": 3,
      "dayIndex": 2
    }
  ],
  "courseBundlePrice": 500,
  "events": [
    {
      "code": "VA27",
      "days": [
        {
          "date": "2027-03-18",
          "label": "Thursday, March 18",
          "hours": "9:00 AM - 6:00 PM"
        },
        {
          "date": "2027-03-19",
          "label": "Friday, March 19",
          "hours": "10:00 AM - 3:00 PM"
        }
      ],
      "preDate": "2027-03-17",
      "courseDates": [
        "2027-03-17",
        "2027-03-18",
        "2027-03-19"
      ],
      "checkoutUrl": null
    },
    {
      "code": "LV27",
      "days": [],
      "preDate": null,
      "courseDates": [],
      "checkoutUrl": null
    },
    {
      "code": "MN27",
      "days": [
        {
          "date": "2027-07-16",
          "label": "Friday, July 16",
          "hours": "9:00 AM - 6:00 PM"
        },
        {
          "date": "2027-07-17",
          "label": "Saturday, July 17",
          "hours": "10:00 AM - 3:00 PM"
        }
      ],
      "preDate": "2027-07-15",
      "courseDates": [
        "2027-07-15",
        "2027-07-16",
        "2027-07-17"
      ],
      "checkoutUrl": null
    }
  ]
};
